### PR TITLE
add dash in travis.yml and also in explanation text

### PR DESCRIPTION
**Pull request by gforsyth**
it was missing in the helper text and so travis defaults to a token
based deploy (and then fails)

### CODE REVIEW

**Comment by asmeurer** [comment]
It worked before like that. Did this actually fix the problem?

**Comment by gforsyth** [comment]
Nope.  I think I just found it though.  When `DOCTR_DEPLOY_ENCRYPTION_KEY` exists then `token = ''` which errors out when it hits a `decode`.  Just pushed up a fix

**Comment by asmeurer** [comment]
Ah damn. The "this should be bytes" vs. "this should be str" trips up the best of us. If only Python had a type checker.

**Comment by gforsyth** [comment]
New project:  A Travis CI based Python type checker

**Pull request merged**
