### PR TITLE
one more shot at this -- branch checking disabled

### PR DESCRIPTION
**Pull request by gforsyth**
reopening this for progress checks

### CODE REVIEW

**Comment by gforsyth** [comment]
Ok, I think that did it.  But we'll see what happens when I merge this in.

**Comment by gforsyth** [comment]
Good news and bad news.  
Good news: This worked (!).  The gh-pages branch has been updated and there are green arrows everywhere

Bad news: the actual static site is 404'ing and I don't know why

**Comment by asmeurer** [comment]
I think it works. You just have to go to http://gforsyth.github.io/doctr/docs. There is no redirect page at http://gforsyth.github.io/doctr/.

**Comment by gforsyth** [comment]
Yay!

**Pull request merged**
